version: '3.9'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cotton-api
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data
    working_dir: /app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  scraper:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: siphon-scraper
    volumes:
      - db_data:/app/data
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "echo '0 1 * * 2 cd /app && python commodity_scraper.py >> /app/scraper.log 2>&1' > /etc/crontabs/root && crond -f -l 2"

  db-gui:
    image: coleifer/sqlite-web
    container_name: siphon-db-gui
    ports:
      - "8080:8080"
    volumes:
      - db_data:/data
    command: "sqlite_web --read-only --host 0.0.0.0 /data/prices.db"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: siphon-frontend
    ports:
      - "3000:80"

  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: siphon-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    depends_on:
      - web
      - frontend

  certbot:
    image: certbot/certbot
    container_name: siphon-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1d; done'"

volumes:
  db_data:
  certbot-etc:
  certbot-web:
