services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cotton-api
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data  
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cotton-scraper
    volumes:
      - db_data:/app/data
    entrypoint: ["/bin/sh", "-c"]
    # Cotlook updates every Monday at ~13:00 GMT, which is 23:00 AEST on Monday
    # Runs every Tuesday at 01:00 to account for time difference and ensure data is fresh 
    command: >
      "echo '0 1 * * 2 cd /app && python cotton_scraper.py >> /app/scraper.log 2>&1' > /etc/crontabs/root && crond -f -l 2"    

  db-gui:
    image: coleifer/sqlite-web
    container_name: cotton-db-gui
    ports:
      - "8080:8080"
    volumes:
      - db_data:/data
    command: "sqlite_web --read-only --host 0.0.0.0 /data/prices.db"

volumes:
  db_data:
