version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/frontend/build
    command: sh -c "npm install && npm run build"
    restart: always

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siphon-scraper
    expose:
      - "8000"
    restart: always

  db-gui:
    image: coleifer/sqlite-web
    container_name: siphon-db-gui
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: always

  proxy:
    image: nginx:1.29-alpine
    container_name: siphon-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html
      - certbot_data:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - scraper
    restart: always

  certbot:
    image: certbot/certbot
    container_name: siphon-certbot
    volumes:
      - certbot_data:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    restart: always

volumes:
  frontend_build:
  certbot_data:
